version: "3.8"
services:
  frontend-app:
    env_file : .env
    
    build:
      dockerfile: "Dockerfile"
      context: .
    image: frontend-app

    container_name: frontend

    ports:
      - 3333:3333
